# ==============================
# Tokyo Neon Picom
# ==============================

backend = "xrender";
vsync = true;

# Shadows
shadow = true;
shadow-radius = 18;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.38;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g = 'Rofi'",
  "class_g = 'Dunst'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Rounded corners
corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# Fading
fading = true;
fade-in-step = 0.045;
fade-out-step = 0.045;
fade-delta = 5;

# Transparency
inactive-opacity = 0.94;
active-opacity = 1.0;
frame-opacity = 0.95;
inactive-opacity-override = false;

opacity-rule = [
  "75:class_g = 'Xfce4-terminal'",
  "94:class_g = 'Alacritty'",
  "100:class_g = 'Code'",
  "100:class_g = 'Brave-browser'",
  "96:class_g = 'Thunar'",
  "98:class_g = 'Rofi'"
];

# Blur can look cool but may be buggy on some GPUs.
# Enable only if performance is good.
#blur-method = "dual_kawase";
#blur-strength = 4;
#blur-background = true;
#blur-background-frame = true;
#blur-background-fixed = false;

#blur-background-exclude = [
#  "window_type = 'dock'",
#  "window_type = 'desktop'",
#  "class_g = 'Rofi'"
#];

# General
detect-client-opacity = true;
detect-rounded-corners = true;
detect-transient = true;
detect-client-leader = true;
use-damage = true;

# Prevent weird focus issues
mark-wmwin-focused = true;
mark-ovredir-focused = true;
